### ISSUE TITLE
place furnace instant crash

### ISSUE THREAD

**Issue by dahjin** [pixlepix/Aura-Cascade#47]
java.lang.NullPointerException: Exception while updating neighbours
	at net.minecraft.block.BlockDoor.func_149695_a(BlockDoor.java:337)
	at net.minecraft.block.BlockDoor.func_149695_a(BlockDoor.java:371)
	at net.minecraft.world.World.func_147460_e(World.java:1087)
	at net.minecraft.world.World.func_147459_d(World.java:1023)
	at net.minecraft.world.World.func_147444_c(World.java:988)
	at pixlepix.auracascade.block.tile.AuraTile.func_145845_h(AuraTile.java:264)
	at net.minecraft.world.World.func_72939_s(World.java:2487)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:664)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pixlepix** [comment]
Yeah, imma need more info on that one ._.

**Comment by dahjin** [comment]
sorry about that 
http://pastebin.com/CheCEtTp

**Comment by pixlepix** [comment]
I mean, what were you doing to cause the crash? Can it be reproduced in a fresh world? What blocks are next to the furnace.

**Comment by dahjin** [comment]
I'm unable to reproduced this as of right now. But i will let you know when it happens again i reset my world so i don't have the same setup i had previously. Sorry.

**Comment by pixlepix** [comment]
Fixed in latest build
